version: 1.3.7-{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
configuration: Release
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
before_build:
- ps: dotnet restore
build:
  project: CoreFtp.sln
  publish_nuget: false
  publish_nuget_symbols: false
  include_nuget_references: false
  parallel: true
  verbosity: minimal
after_build:
- ps: dotnet pack src\CoreFTP\CoreFTP.csproj --no-build --configuration Release
test: off
artifacts:
- path: src\CoreFtp\bin\Release\CoreFtp.*.nupkg
