version: 1.3.5-{build}
image: Visual Studio 2017 RC
pull_requests:
  do_not_increment_build_number: true
configuration: Release
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
before_build:
- ps: dotnet restore
build:
  project: CoreFtp.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
test: off
artifacts:
- path: src\CoreFtp\bin\Release\CoreFtp.*.nupkg
